### ISSUE TITLE
How to pass in handler_call_details in the interceptor.

### ISSUE THREAD

**Issue by sp1rs** [d5h-foss/grpc-interceptor#7]
Through the interceptor we get in `method`, `request`, `context` and `method_name`. Is there a way to access `handler_call_details` also?

**Comment by d5h** [comment]
Hi @sp1rs,

It’s not currently passed through, but could be added. What’s the use case? I assume you need the metadata?

**Comment by sp1rs** [comment]
Yes, It is required for the metadata. And also what is the right way to set the data? where to set the data?
For example, in every request, the user token is received, from that, we fetch the user. From that, I would like to store the user info. Should It be part of the `context`?

**Comment by d5h** [comment]
The metadata is also available via [`context.invocation_metadata()`](https://grpc.github.io/grpc/python/grpc.html#grpc.ServicerContext.invocation_metadata).

Passing data to the service is probably best done via the `context` as you mentioned. You might want to subclass or wrap `ServicerContext` to add custom methods related to user auth and management. Something like this:

```python
def intercept(self, method, request, context, method_name):
    metadata = context.invocation_metadata()
    custom_context = CustomContext(context)
    custom_context.set_user_from_metadata(metadata)
    return method(request, custom_context)
```

**Comment by d5h** [comment]
I'm going to go ahead and close this since I think the workaround is sufficient.
